### ISSUE TITLE
Add project website

### ISSUE THREAD

**Issue by ll-nick** [KIT-MRT/arbitration_graphs#33]
Hosting a static website via github.io shouldn't be a huge amount of effort but is way cooler than having just the readme.

**Comment by orzechow** [comment]
There's a ton of tools for Markdown to Webpage generation.
Most render the markdown file(s) to a static HTML page
- pro: fast and robust website
- con: needs some kind of CI/CD (GitHub Workflow)
- pro/con: usually needs distinct doc files 

Some render the Markdown even fully on the client side via JavaScript
- pro: no compilation necessary
- pro: one can simply use an existing `Readme.md`
- con: slower on the client side and might be less robust

A (somewhat arbitrary) collection:

[Vitepress](https://vitepress.dev/)
- [Starship.rs](https://starship.rs) uses Vitepress to generate their beautiful website
- [Simple Markdown header](https://github.com/starship/starship/blob/master/.github/workflows/publish-docs.yml) defines theme, metadata etc.
- [GitHub Pages deployment](https://vitepress.dev/guide/deploy#github-pages)

[MKDocs](https://www.mkdocs.org/)
- root mkdocs.yml defines theme, metadata etc.
- a lot of [themes](https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes)
- [GitHub Pages deployment](https://www.mkdocs.org/user-guide/deploying-your-docs/#github-pages)

[zero-md](https://zerodevx.github.io/zero-md/) (based on [marked](https://github.com/markedjs/marked))
- client side rendering
- very simple usage
- nice default theme

**Comment by orzechow** [comment]
I'd first try it with zero-md, as this could bring a really nice efford/result tradeoff :grinning:

**Comment by orzechow** [comment]
I briefly tried out zero-md and GitHub Pages directly.

Turns out zero-md provides the theme and rendering for the markdown page in itself, but does not layout an appropriate page container. For a use case as ours, is intended to be used together with [zero-md-docs](https://github.com/zerodevx/zero-md-docs). That again assumes the whole docs to be placed in `/docs`

<details>
<summary>As a result, the zero-md only page looks like this</summary>

![Screenshot 2024-09-23 at 21-17-18 ](https://github.com/user-attachments/assets/ff897ffc-929f-4974-8dd9-efb935962664)

</details>

---

GitHub also features rendering of the Markdown Pages with a GitHub renderer directly and provides a [selection of themes](https://pages.github.com/themes/). External themes can be used as well.
As this allows reusing the root `Readme.md` I gave it a shot.

<details>
<summary>Without any more styling, this is how our Page looks with the Cayman theme.</summary>

![Screenshot 2024-09-23 at 21-44-57 ARBITRATION GRAPHS arbitration_graphs](https://github.com/user-attachments/assets/80e9a4fd-ce98-41c0-b35c-83a004a123c8)

</details>

I'd change colors, hero background image etc. but overall I like the theme regarding page layout, font etc.

**Comment by orzechow** [comment]
See https://github.com/KIT-MRT/arbitration_graphs/pull/50

**Comment by orzechow** [comment]
@ll-nick How do you like the Cayman theme?

**Comment by orzechow** [comment]
Alright, I played around with colors, fonts and code highlighter themes. 

<details>
<summary>That's my best approach</summary>

![Screenshot 2024-10-04 at 19-11-55 Cayman theme Cayman is a clean responsive theme for GitHub Pages](https://github.com/user-attachments/assets/d0f7d23e-07f0-4d9f-b517-945fb25fc0ea)

</details>

These changes are still in the generic cayman theme repo (was the easiest to setup for testing):
[orzechow/cayman@style_for_arbitration_graphs](https://github.com/orzechow/cayman/tree/style_for_arbitration_graphs)

So, I still need to transfer this to our page.

@ll-nick Are you fine with the theme?

**Comment by ll-nick** [comment]
Look great! :heart:

**Comment by orzechow** [comment]
Alright, PR is ready: #50
